version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: yakovlevkirevg/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: yakovlevkirevg/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    image: yakovlevkirevg/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/media
    ports:
      - 9000:80
